# Generated by Django 5.0.7 on 2024-07-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_note_userexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexercise',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='user',
        ),
    ]
