# Generated by Django 5.0.7 on 2024-07-27 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.workout'),
        ),
    ]
