# Generated by Django 5.0.7 on 2024-07-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_set_remove_userexercise_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='sets',
        ),
    ]
