# Generated by Django 5.0.7 on 2024-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_set_user_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
