# Generated by Django 5.0.7 on 2024-07-31 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_workout_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='user_exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='api.userexercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
