# Generated by Django 5.0.7 on 2024-07-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_set_user_exercise_alter_workout_workout_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='ExerciseSet',
        ),
    ]
