# Generated by Django 5.0.7 on 2024-07-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userexercise_workout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexercise',
            old_name='exercise',
            new_name='user_exercise',
        ),
    ]
